# Notes

[Reinforcement Learning Article](https://towardsdatascience.com/reinforcement-learning-explained-visually-part-5-deep-q-networks-step-by-step-5a5317197f4b)


# Environment Setup


## Import Modules


In [1]:
import numpy as np
import tensorflow as tf
from random import Random
from functools import reduce


## Move Methods

So I did some syntax lessons

In [2]:
class Move:
    def __init__(
        self, name: str, loops: list[list[int]], two: bool = False, prime: bool = False
    ):
        self.name = name
        self.matrix: np.ndarray = np.identity(9 * 6, dtype=np.int8)
        for loop in loops:
            first = np.copy(self.matrix[loop[0]])
            for i in range(len(loop) - 1):
                self.matrix[loop[i]] = self.matrix[loop[i + 1]]
            self.matrix[loop[-1]] = first
        if two:
            self.matrix = self.matrix @ self.matrix
        if prime:
            self.matrix = self.matrix.T
        


def build_moves(letter: str, loops: list[list[int]]) -> list[Move]:
    return [
        Move(letter, loops),
        Move(f"{letter}P", loops, prime=True),
        Move(f"{letter}2", loops, two=True),
    ]

# Behold, python syntax
MOVES = [
    move
    for moves in [
        build_moves(
            "R",
            [
                [20, 2, 42, 47],
                [23, 5, 39, 50],
                [26, 8, 36, 53],
                [27, 29, 35, 33],
                [28, 32, 34, 30],
            ],
        ),
        build_moves(
            "U",
            [
                [20, 11, 38, 29],
                [19, 10, 37, 28],
                [18, 9, 36, 27],
                [8, 6, 0, 2],
                [7, 3, 1, 5],
            ],
        ),
        build_moves(
            "L",
            [
                [18, 45, 44, 0],
                [21, 48, 41, 3],
                [24, 51, 38, 6],
                [11, 17, 15, 9],
                [14, 16, 12, 10],
            ],
        ),
        build_moves(
            "D",
            [
                [24, 33, 42, 15],
                [25, 34, 43, 16],
                [26, 35, 44, 17],
                [45, 47, 53, 51],
                [46, 50, 52, 48],
            ],
        ),
        build_moves(
            "F",
            [
                [6, 27, 47, 17],
                [7, 30, 46, 14],
                [8, 33, 45, 11],
                [18, 20, 26, 24],
                [19, 23, 25, 21],
            ],
        ),
        build_moves(
            "B",
            [
                [36, 38, 44, 42],
                [37, 41, 43, 39],
                [29, 0, 15, 53],
                [32, 1, 12, 52],
                [35, 2, 9, 51],
            ],
        ),
    ]
    for move in moves
]

## The Cube Environment


In [3]:
def new_cube():
    state = np.zeros((9 * 6), dtype=np.int8)
    for i in range(state.size):
        state[i] = i / 9
    return state


def apply_move(state, move: Move) -> np.ndarray:
    return state @ move.matrix


def scramble(state: np.ndarray, count: int) -> np.ndarray:
    random = Random()
    return state @ reduce(
        lambda a, b: a @ b, [random.choice(MOVES).matrix for i in range(count)]
    )


# Machine Learning Setup


## Constants


In [4]:
EPSILON = 0.5
"The chance that the agent will choose to explore instead of picking the best answer"


'The chance that the agent will choose to explore instead of picking the best answer'

## Converting State to Vector

In order to make an accurate network, we will need to convert the cube's state array to a longer array to make it clearer to the network what color is where


In [5]:
def state_to_vector(state):
    vector = np.zeros((9 * 6 * 6,1),dtype=np.float32)
    for i in range(9 * 6):
        color = state[i]
        vector[i * 6 + color] = 1
    return vector.T
        

## The Neural Network


In [6]:
def random_network(sizes: list[int]) -> list[tuple[(tf.Variable, tf.Variable)]]:
    sizes = sizes + [len(MOVES)]
    values = []
    for i in range(len(sizes)):
        size = sizes[i]
        prev_size = 9 * 6 * 6
        if i > 0:
            prev_size = sizes[i - 1]
        weights = tf.Variable(
            tf.random.normal([prev_size, size], stddev=0.03), name=f"W{i+1}"
        )
        constants = tf.Variable(tf.random.normal([size]), name=f"b{i+1}")
        values.append((weights, constants))
    return values


def feed_network(state, network: list[tuple[(tf.Variable, tf.Variable)]]):
    x = tf.cast(state, tf.float32)
    for i in range(len(network)):
        W, b = network[i]
        if i > 0:
            x = tf.nn.relu(x)
        x = tf.add(tf.matmul(x, W), b)
    return x


def copy_network(network: list[tuple[(tf.Variable, tf.Variable)]]):
    copy = []
    for layer in network:
        W, b = layer
        copy.append((np.copy(W), np.copy(b)))
    return copy

## Reward Function

In [7]:
def get_reward(state: np.ndarray):
    value = 0
    for i in range(9 * 6):
        if state[i] == i // 9:
            value = value + 1
        else:
            value = value - 1
    return value

## Replay Database


In [48]:
def create_replay(network: list[tuple[(tf.Variable, tf.Variable)]], count: int, epsilon: float = EPSILON):
    replays: list[
        tuple[
            (
                np.ndarray,  # current state
                Move,  # action
                np.ndarray,  # next state
                tf.float32,  # Q-Value
            )
        ]
    ] = []

    random = Random()

    cube = scramble(new_cube(), 1000)

    for i in range(count):
        choice: Move = None
        if random.random() < epsilon:
            choice = random.choice(MOVES)
        else:
            q_vals = feed_network(state_to_vector(cube), network)
            index_max = tf.argmax(q_vals,1).numpy()[0]
            choice = MOVES[index_max]
        new_state = apply_move(cube,choice)

        replays.append((
            cube,
            choice,
            new_state,
            get_reward(new_state)
        ))
        cube = new_state
                

    return replays

create_replay(random_network([100,10,4,23,45]),10000)

[(array([5, 3, 0, 1, 0, 0, 4, 1, 3, 4, 2, 3, 5, 1, 3, 2, 5, 1, 5, 0, 2, 2,
         2, 5, 2, 1, 3, 5, 4, 4, 2, 3, 4, 0, 3, 1, 1, 0, 1, 3, 4, 4, 0, 2,
         3, 5, 4, 4, 1, 5, 5, 0, 0, 2], dtype=int8),
  array([5, 3, 0, 1, 0, 0, 4, 1, 3, 4, 2, 3, 5, 1, 3, 0, 2, 3, 5, 0, 2, 2,
         2, 5, 2, 5, 1, 5, 4, 4, 2, 3, 4, 2, 1, 3, 1, 0, 1, 3, 4, 4, 0, 3,
         1, 0, 1, 5, 0, 5, 4, 2, 5, 4], dtype=int8),
  -24),
 (array([5, 3, 0, 1, 0, 0, 4, 1, 3, 4, 2, 3, 5, 1, 3, 0, 2, 3, 5, 0, 2, 2,
         2, 5, 2, 5, 1, 5, 4, 4, 2, 3, 4, 2, 1, 3, 1, 0, 1, 3, 4, 4, 0, 3,
         1, 0, 1, 5, 0, 5, 4, 2, 5, 4], dtype=int8),
  array([5, 3, 5, 1, 0, 4, 4, 1, 4, 4, 2, 3, 5, 1, 3, 0, 2, 3, 5, 0, 0, 2,
         2, 3, 2, 5, 1, 3, 1, 2, 4, 3, 2, 4, 4, 5, 1, 0, 1, 5, 4, 4, 2, 3,
         1, 0, 1, 0, 0, 5, 0, 2, 5, 3], dtype=int8),
  -32),
 (array([5, 3, 5, 1, 0, 4, 4, 1, 4, 4, 2, 3, 5, 1, 3, 0, 2, 3, 5, 0, 0, 2,
         2, 3, 2, 5, 1, 3, 1, 2, 4, 3, 2, 4, 4, 5, 1, 0, 1, 5, 4, 4, 2, 3,
         1, 0, 1, 0, 0